---

- name: Install Packages
  yum:
    name:
      - epel-release
      - httpd
      - php
      - php-mysql
    state: present

- name: restart and enable systemd nginx service
  systemd:
    name: httpd
    enabled: yes
    state: restarted

- name: Allow http port
  firewalld:
    port: http
    permanent: yes
    state: enabled

- name: Give writable mode to http folder
  file:
   path: /var/www/html
   state: directory
   mode: 0755

- name: Clone a repo with separate git directory
  git:
    repo: https://github.com/ludovic-tech/app-php.git
    dest: /var/www/html


- name: Allow http port
  firewalld:
    port: http
    permanent: yes
    state: enabled

- name: restart and enable systemd nginx service
  systemd:
    name: httpd
    enabled: yes
    state: enabled

# tasks file for apache


# FROM https://phoenixnap.com/kb/how-to-install-lamp-stack-on-centos
