---

- name: install mariadb package
  yum:
   name: 
    - mariadb
    - mariadb-server
   state: present

- name: restart and enable systemd nginx service
  systemd:
    name: mariadb
    enabled: yes
    state: restarted

#- name: Start mysql_secure_installation
#  command: "mysql --user=root --password=Myrootpasswd -connect-expired-password --execute=\"ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ root_password }}; grant all privileges on *.*# to 'root'@'localhost' with grant option;"

- name: restart and enable systemd nginx service
  systemd:
    name: mariadb
    enabled: yes
    state: enabled


# tasks file for mariadb


